### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by mLuby** [taskworld/atom-lcov#2]
Caused by opening command palette and selecting `Atom Lcov: Select`

```
/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:77

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readFile (fs.js:262:11)
    at Object.fs.readFile (ELECTRON_ASAR.js:374:25)
    at refresh (/Users/myUser/.atom/packages/atom-lcov/lib/atom-lcov.js:16:12)
    at AnonymousObservable.__subscribe (/Users/myUser/.atom/packages/atom-lcov/lib/atom-lcov.js:12:7)
    at AnonymousObservable.tryCatcher (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:63:31)
    at setDisposable [as action] (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:5845:44)
    at ScheduledItem.invokeCore (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:896:33)
    at ScheduledItem.invoke (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:884:40)
    at runTrampoline (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:1125:37)
    at tryCatcher (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:63:31)
    at CurrentThreadScheduler.schedule (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:1141:45)
    at AnonymousObservable.Rx.AnonymousObservable.AnonymousObservable._subscribe (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:5860:32)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:2034:19)
    at SwitchObserver.next (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:3964:35)
    at SwitchObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:1762:31)
    at SwitchObserver.tryCatcher (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:2145:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:1762:31)
    at Subject.Rx.Subject.addProperties.onNext (/Users/myUser/.atom/packages/atom-lcov/node_modules/rx/dist/rx.js:5998:19)
    at Object.selectFile (/Users/myUser/.atom/packages/atom-lcov/lib/atom-lcov.js:93:20)
    at atom-workspace.atomLcovSelect (/Users/myUser/.atom/packages/atom-lcov/lib/atom-lcov.js:74:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
```

**Comment by mLuby** [comment]
closing as dup of #1
